name: Update Databricks Workspace Repo
on: 
  push:
    branches: main
jobs:
  Refresh-Workspace-Repo:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - run: |
          curl -X PATCH "${{ vars.WORKSPACE_URL }}/api/2.0/repos/${{ vars.REPO_ID }}" -H "Authorization: Bearer ${{ secrets.DATABRICKS_PAT }}" -H "Content-Type: application/json" -d '{ "branch": "main" }'
