name: Update Databricks Workspace Repo
on: 
  push:
    branches: main
jobs:
  Refresh-Workspace-Repo:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - run: |
          curl -H "Authorization: Bearer ${{ secrets.DATABRICKS_PAT }}" "${{ vars.WORKSPACE_URL }}/api/2.0/repos/${{ vars.REPO_ID }}"
